'use client';

export const tableDataSettlement = {
  columns: [
    { label: 'No.' },
    { label: 'No. Tiket' },
    { label: 'Tanggal Keluar' },
    { label: 'Pintu Keluar' },
    { label: 'Nopol' },
    { label: 'Kendaraan' },
    { label: 'Interval' },
    { label: 'Tarif' },
    { label: 'Denda' },
    { label: 'Tipe Denda' },
    { label: 'Pembayaran' },
    { label: 'Channel' },
    { label: 'VA / QR' },
    { label: 'Petugas' },
    { label: 'Shift' },
    { label: 'Transaction ID' },
    { label: 'Order ID' },
    { label: 'Transaction Time' },
    { label: 'Settlement Time' },
    { label: 'Settlement Status' },
    { label: 'File Settlement Name' },
    { label: 'Aksi' },
  ],
  rows: [
    {
      no: '1',
      noTiket: 'TK-001',
      tanggalKeluar: '2025-05-09 14:10',
      pintuKeluar: 'Gate A',
      nopol: 'B 1234 ABC',
      kendaraan: 'Mobil',
      interval: '2 jam',
      tarif: 'Rp 10.000',
      denda: 'Rp 0',
      tipeDenda: 'Tidak Ada',
      pembayaran: 'QRIS',
      channel: 'GoPay',
      vaQr: 'INV001QR001',
      petugas: 'Riki',
      shift: 'A',
      transactionId: 'mid-001',
      orderId: 'ORD-001',
      transactionTime: '2025-05-09 14:08',
      settlementTime: '2025-05-10 10:00',
      settlementStatus: 'settled',
      fileSettlementName: 'settlement_20250510.csv',
    },
    {
      no: '2',
      noTiket: 'TK-002',
      tanggalKeluar: '2025-05-09 15:45',
      pintuKeluar: 'Gate B',
      nopol: 'D 4567 XYZ',
      kendaraan: 'Motor',
      interval: '1 jam',
      tarif: 'Rp 5.000',
      denda: 'Rp 0',
      tipeDenda: 'Tidak Ada',
      pembayaran: 'VA',
      channel: 'Mandiri VA',
      vaQr: 'VA0019981827',
      petugas: 'Yudi',
      shift: 'A',
      transactionId: 'mid-002',
      orderId: 'ORD-002',
      transactionTime: '2025-05-09 15:43',
      settlementTime: '2025-05-10 10:00',
      settlementStatus: 'settled',
      fileSettlementName: 'settlement_20250510.csv',
    },
    {
      no: '3',
      noTiket: 'TK-003',
      tanggalKeluar: '2025-05-09 17:30',
      pintuKeluar: 'Gate C',
      nopol: 'F 7890 TUV',
      kendaraan: 'Mobil',
      interval: '3 jam',
      tarif: 'Rp 15.000',
      denda: 'Rp 2.000',
      tipeDenda: 'Kehilangan Tiket',
      pembayaran: 'E-Wallet',
      channel: 'OVO',
      vaQr: 'OVO9992838',
      petugas: 'Alya',
      shift: 'B',
      transactionId: 'mid-003',
      orderId: 'ORD-003',
      transactionTime: '2025-05-09 17:27',
      settlementTime: '2025-05-10 10:00',
      settlementStatus: 'settled',
      fileSettlementName: 'settlement_20250510.csv',
    },
    {
      no: '4',
      noTiket: 'TK-004',
      tanggalKeluar: '2025-05-09 20:00',
      pintuKeluar: 'Gate D',
      nopol: 'B 1235 DEF',
      kendaraan: 'Mobil',
      interval: '2.5 jam',
      tarif: 'Rp 12.000',
      denda: 'Rp 0',
      tipeDenda: 'Tidak Ada',
      pembayaran: 'QRIS',
      channel: 'ShopeePay',
      vaQr: 'SPAY101928',
      petugas: 'Tina',
      shift: 'B',
      transactionId: 'mid-004',
      orderId: 'ORD-004',
      transactionTime: '2025-05-09 19:59',
      settlementTime: '2025-05-10 10:00',
      settlementStatus: 'failed',
      fileSettlementName: 'settlement_20250510.csv',
    },
    {
      no: '5',
      noTiket: 'TK-005',
      tanggalKeluar: '2025-05-09 22:15',
      pintuKeluar: 'Gate A',
      nopol: 'H 6543 JKL',
      kendaraan: 'Motor',
      interval: '1.5 jam',
      tarif: 'Rp 7.000',
      denda: 'Rp 0',
      tipeDenda: 'Tidak Ada',
      pembayaran: 'Payment Gateway',
      channel: 'Credit Card',
      vaQr: 'CCPAY20250509',
      petugas: 'Nina',
      shift: 'C',
      transactionId: 'mid-005',
      orderId: 'ORD-005',
      transactionTime: '2025-05-09 22:13',
      settlementTime: '2025-05-10 10:00',
      settlementStatus: 'pending',
      fileSettlementName: 'settlement_20250510.csv',
    },
  ],
};
