//tabelDataPos.js
'use client';

export const tableDataPos = {
  columns: [
    { label: 'No.' },
    { label: 'Kode' },
    { label: 'Keterangan' },
    { label: 'Tipe Pos' },
    { label: 'Tipe Manless' },
    { label: 'Tipe Kendaraan' },
    { label: 'Kamera 1?' },
    { label: 'Kamera 2?' },
    { label: 'Printer Name' },
    { label: 'Interface Name' },
    { label: 'COM Port' },
    { label: 'Otorisasi?' },
    { label: 'Synchronize (Menit)' },
    { label: 'Added' },
    { label: 'Updated' },
    { label: 'Aksi' },
  ],
  rows: [
    {
      no: '1',
      kode: 'PK1',
      keterangan: 'Pos Masuk 1',
      tipePos: 'Out',
      tipeManless: '-',
      tipeKendaraan: 'All',
      kamera1: true,
      kamera2: true,
      printerName: 'EPSON TM-T80 Receipt',
      interfaceName: 'BGI',
      comPort: 'COM1',
      otorisasi: true,
      synchronize: '7',
      added: '17-11-2021 23:29',
      updated: 'Muhtar Lubis Asyari 17-11-2021 23:45',
      aksi: 'PK1',
    },
    {
      no: '2',
      kode: 'PK2',
      keterangan: 'Pos Keluar All',
      tipePos: 'Out',
      tipeManless: '-',
      tipeKendaraan: 'All',
      kamera1: true,
      kamera2: false,
      printerName: 'EPSON TM-T81 Receipt',
      interfaceName: 'BGI',
      comPort: 'COM1',
      otorisasi: true,
      synchronize: '5',
      added: '17-11-2021 23:29',
      updated: 'Master 19-12-2023 21:57',
      aksi: 'PK2',
    }, {
      no: '3',
      kode: 'PM1',
      keterangan: 'Pos Masuk 2',
      tipePos: 'In',
      tipeManless: 'Tidak',
      tipeKendaraan: 'Motor',
      kamera1: false,
      kamera2: true,
      printerName: 'Canon MX-360',
      interfaceName: 'Serial',
      comPort: 'COM3',
      otorisasi: false,
      synchronize: '10',
      added: '10-03-2022 10:15',
      updated: '-',
      aksi: 'PM1',
    },
    {
      no: '4',
      kode: 'PM2',
      keterangan: 'Pos Keluar 2',
      tipePos: 'Out',
      tipeManless: 'Ya',
      tipeKendaraan: 'Motor',
      kamera1: true,
      kamera2: true,
      printerName: 'HP LaserJet',
      interfaceName: 'USB',
      comPort: 'COM4',
      otorisasi: true,
      synchronize: '8',
      added: '05-06-2022 14:20',
      updated: '-',
      aksi: 'PM2',
    },
    {
      no: '5',
      kode: 'PK3',
      keterangan: 'Pos VIP',
      tipePos: 'In/Out',
      tipeManless: 'Ya',
      tipeKendaraan: 'All',
      kamera1: true,
      kamera2: false,
      printerName: 'Brother HL-L2350DW',
      interfaceName: 'USB',
      comPort: 'COM5',
      otorisasi: true,
      synchronize: '3',
      added: '30-09-2022 17:45',
      updated: 'Admin 01-10-2022 18:30',
      aksi: 'PK3',
    },
    {
      no: '6',
      kode: 'PK4',
      keterangan: 'Pos Masuk Parkir Basement',
      tipePos: 'In',
      tipeManless: '-',
      tipeKendaraan: 'Mobil',
      kamera1: false,
      kamera2: false,
      printerName: 'Epson LX-350',
      interfaceName: 'Parallel',
      comPort: 'COM6',
      otorisasi: false,
      synchronize: '6',
      added: '15-01-2023 08:10',
      updated: '-',
      aksi: 'PK4',
    },
    {
      no: '7',
      kode: 'PK5',
      keterangan: 'Pos Keluar Parkir Basement',
      tipePos: 'Out',
      tipeManless: 'Ya',
      tipeKendaraan: 'Mobil',
      kamera1: true,
      kamera2: true,
      printerName: 'Samsung ML-1660',
      interfaceName: 'BGI',
      comPort: 'COM7',
      otorisasi: true,
      synchronize: '4',
      added: '23-05-2023 12:30',
      updated: 'Admin 24-05-2023 13:45',
      aksi: 'PK5',
    },
  ],
};
