export const tableDataGlobal = {
  columns: [
    { label: 'No.' },
    { label: 'Nama Operator' },
    { label: 'Email Operator' },
    { label: 'Telp Operator' },
    { label: 'Fax Operator' },
    { label: 'Alamat Operator' },
    { label: 'Nama Lokasi' },
    { label: 'Email Lokasi' },
    { label: 'Telp Lokasi' },
    { label: 'Fax Lokasi' },
    { label: 'Alamat Lokasi' },
    { label: 'Aksi' },
  ],
  rows: [
    {
      no: 1,
      id: 1,
      nama_operator: 'PT. Parkir Nusantara',
      email_operator: 'info@parkirnusantara.co.id',
      no_telp_operator: '021-12345678',
      no_fax_operator: '021-87654321',
      alamat_operator: 'Jl. Merdeka No. 123, Jakarta',

      nama_lokasi: 'Gedung Parkir A',
      email_lokasi: 'lokasia@parkir.co.id',
      no_telp_lokasi: '021-22334455',
      no_fax_lokasi: '021-55443322',
      alamat_lokasi: 'Jl. Veteran No. 99, Jakarta',
    }
    // ,
    // {
    //   no: 2,
    //   id: 2,
    //   nama_operator: 'CV. Aman Sentosa',
    //   email_operator: 'admin@amansentosa.com',
    //   no_telp_operator: '022-98765432',
    //   no_fax_operator: '022-12345678',
    //   alamat_operator: 'Jl. Soekarno Hatta No. 45, Bandung',

    //   nama_lokasi: 'Mall Central Parkir',
    //   email_lokasi: 'mallcentral@parkir.co.id',
    //   no_telp_lokasi: '022-44556677',
    //   no_fax_lokasi: '022-77665544',
    //   alamat_lokasi: 'Jl. Sudirman No. 88, Bandung',
    // },
    // {
    //   no: 3,
    //   id: 3,
    //   nama_operator: 'PT. Sinar Abadi',
    //   email_operator: 'kontak@sinarabadi.co.id',
    //   no_telp_operator: '031-12398765',
    //   no_fax_operator: '031-56789123',
    //   alamat_operator: 'Jl. Diponegoro No. 77, Surabaya',

    //   nama_lokasi: 'Stasiun Timur',
    //   email_lokasi: 'timur@parkir.co.id',
    //   no_telp_lokasi: '031-22334455',
    //   no_fax_lokasi: '031-99887766',
    //   alamat_lokasi: 'Jl. Kenjeran No. 101, Surabaya',
    // },
  ],
};
