export const tableDataGlobal = {
  columns: [
    { label: "No." },
    { label: "Nama" },
    { label: "Nilai" },
    { label: "Keterangan" },
    { label: "Updated" },
    { label: "Aksi" },
  ],
  rows: [
    {
      no: "1",
      nama: "Mobil",
      nilai: "Rp. 50.000",
      keterangan: "Rp. 0",
      updated: "Administrator 03-11-2022 23:59",
    },
    {
      no: "2",
      nama: "Foto Pintu Masuk",
      nilai: "\\\\192.168.1.100\\photos",
      keterangan: "Lokasi foto untuk pintu masuk",
      updated: "Muhtar Lubis Asyari 18-11-2022 21:39",
    },
    {
      no: "3",
      nama: "Foto Pintu Keluar",
      nilai: "\\\\192.168.1.100\\photos",
      keterangan: "Lokasi foto untuk pintu keluar",
      updated: "Muhtar Lubis Asyari 18-11-2022 21:39",
    },
    {
      no: "4",
      nama: "Default Nomor Polisi",
      nilai: "B",
      keterangan: "Kode nomor polisi wilayah",
      updated: "Muhtar Lubis Asyari 12-07-2022 11:00",
    },
    {
      no: "5",
      nama: "Waktu Minimal Durasi Parkir",
      nilai: "-1",
      keterangan: "Untuk penyesuaian tarif minimal",
      updated: "Muhtar Lubis Asyari 12-07-2022 11:00",
    },
    {
      no: "6",
      nama: "Nama Komputer Server",
      nilai: "\\\\Server-pc",
      keterangan: "Digunakan untuk sinkronisasi waktu",
      updated: "Muhtar Lubis Asyari 12-07-2022 11:00",
    },
    {
      no: "7",
      nama: "Autocomplete Nopol Member",
      nilai: "FALSE",
      keterangan: "Digunakan untuk autotext ketika mengetikan nopol",
      updated: "Muhtar Lubis Asyari 12-07-2022 11:00",
    },
    {
      no: "8",
      nama: "Bayar Member Ketika Keluar",
      nilai: "FALSE",
      keterangan: "Pengaturan mekanisme pembayaran untuk member",
      updated: "Muhtar Lubis Asyari 12-07-2022 11:00",
    },
    {
      no: "9",
      nama: "Reset Tarif Setelah 1 x 24 Jam",
      nilai: "TRUE",
      keterangan: "Kenakan tarif mulai dari pertama kali setelah 24 Jam",
      updated: "Muhtar Lubis Asyari 02-01-2022 12:06",
    },
    {
      no: "10",
      nama: "Aktif Tarif Maksimal",
      nilai: "TRUE",
      keterangan: "Penggunaan tarif maksimal jika diinginkan",
      updated: "Muhtar Lubis Asyari 12-07-2022 11:00",
    },
    {
      no: "11",
      nama: "Bayar Member Secara Berjenjang",
      nilai: "FALSE",
      keterangan: "Pembayaran member secara berjenjang ketika keluar",
      updated: "Muhtar Lubis Asyari 12-07-2022 11:00",
    },
  ],
};
