export const tableDataPengaduan = {
  columns: [
    { label: "No." },
    { label: "Judul" },
    { label: "Tanggal Masalah" },
    { label: "Kategori Masalah" },
    { label: "Pos" },
    { label: "Alat yang Bermasalah" },
    { label: "Penyebab" },
    { label: "Keterangan Masalah" },
    { label: "Pelapor" },
    { label: "Tanggal Perbaikan" },
    { label: "Jenis Perbaikan" },
    { label: "Penanganan" },
    { label: "Keterangan Perbaikan" },
    { label: "Yang Menangani" },
    { label: "Status" }, // Menggunakan nilai boolean
    { label: "Aksi" },
  ],
  rows: [
    {
      no: "1",
      judul: "Komputer Tidak Menyala",
      tanggal_masalah: "24-04-2025",
      kategori_masalah: "Perangkat Keras",
      pos: "Kantor Administrasi",
      alat_bermasalah: "Unit PC-001",
      penyebab: "Kabel daya rusak",
      keterangan_masalah: "Komputer tidak dapat dinyalakan setelah restart",
      pelapor: "Staff Administrasi",
      tanggal_perbaikan: "25-04-2025",
      jenis_perbaikan: "Penggantian Kabel",
      penanganan: "Ganti kabel daya dengan yang baru",
      keterangan_perbaikan: "PC sudah dapat digunakan kembali",
      yang_menangani: "Teknisi Hardware",
      status: true, // Selesai
    },
    {
      no: "2",
      judul: "Sensor Pintu Gerbang Tidak Berfungsi",
      tanggal_masalah: "24-04-2025",
      kategori_masalah: "Sensor Gerbang",
      pos: "Gerbang Utama",
      alat_bermasalah: "Sensor RFID",
      penyebab: "Sensor rusak dan perlu kalibrasi ulang",
      keterangan_masalah: "Sensor tidak mendeteksi kendaraan",
      pelapor: "Operator Gerbang",
      tanggal_perbaikan: "26-04-2025",
      jenis_perbaikan: "Kalibrasi Sensor",
      penanganan: "Sensor dikalibrasi ulang dan dites ulang",
      keterangan_perbaikan: "Sensor kini mendeteksi kendaraan dengan baik",
      yang_menangani: "Teknisi Elektronik",
      status: true, // Selesai
    },
    {
      no: "3",
      judul: "Jaringan Internet Terputus",
      tanggal_masalah: "23-04-2025",
      kategori_masalah: "Jaringan Komputer",
      pos: "Pos Keamanan",
      alat_bermasalah: "Switch Network",
      penyebab: "Switch jaringan mati",
      keterangan_masalah: "Tidak ada koneksi internet di area gerbang",
      pelapor: "Staff IT",
      tanggal_perbaikan: "23-04-2025",
      jenis_perbaikan: "Penggantian Switch",
      penanganan: "Switch diganti dengan unit baru",
      keterangan_perbaikan: "Jaringan kembali normal",
      yang_menangani: "Teknisi Jaringan",
      status: false, // Belum selesai
    },
  ],
};
