'use client';

export const tableDataPerusahaan = {
  columns: [
    { label: 'No.' },
    { label: 'Nama' },
    { label: 'Jenis Perusahaan' },
    { label: 'Kontak' },
    { label: 'Status' },
    { label: 'Added' },
    { label: 'Updated' },
    { label: 'Aksi' },
  ],
  rows: [
    {
      no: '1',
      nama: 'PT. KAS',
      jenisPerusahaan: 'Pemilik Gedung',
      kontak: '-',
      status: true,
      added: 'Muth 31-10-2022 14:39',
      updated: '-',
      aksi: '1',
    },
    {
      no: '2',
      nama: 'CV. Tech Solution',
      jenisPerusahaan: 'Tenant',
      kontak: '0812-3456-7890',
      status: true,
      added: 'Admin 12-03-2024 14:45',
      updated: '-',
      aksi: '2',
    },
    {
      no: '3',
      nama: 'PT. Digital Corp',
      jenisPerusahaan: 'Developer',
      kontak: '0813-5678-9012',
      status: true,
      added: 'Admin 15-03-2024 08:30',
      updated: '-',
      aksi: '3',
    },
    {
      no: '4',
      nama: 'PT. Inovasi Bangunan',
      jenisPerusahaan: 'Pemilik Gedung',
      kontak: '021-9876543',
      status: true,
      added: 'Admin 18-03-2024 09:20',
      updated: '-',
      aksi: '4',
    },
    {
      no: '5',
      nama: 'CV. Kreatif Mandiri',
      jenisPerusahaan: 'Tenant',
      kontak: '021-7654321',
      status: true,
      added: 'Admin 20-03-2024 11:10',
      updated: '-',
      aksi: '5',
    },
    {
      no: '6',
      nama: 'PT. Infrastruktur Nusantara',
      jenisPerusahaan: 'Developer',
      kontak: '0812-6789-3456',
      status: false,
      added: 'Admin 22-03-2024 13:45',
      updated: '-',
      aksi: '6',
    },
    {
      no: '7',
      nama: 'PT. Global Realty',
      jenisPerusahaan: 'Pemilik Gedung',
      kontak: '021-4567890',
      status: true,
      added: 'Admin 25-03-2024 15:30',
      updated: '-',
      aksi: '7',
    },
  ],
};
