'use client';

export const tableDataKendaraanIn = {
  columns: [
    { label: 'No.' },
    { label: 'No. Tiket' },
    { label: 'Tanggal Masuk' },
    // { label: 'Tanggal Keluar' },
    { label: 'Nopol' },
    { label: 'Kendaraan' },
    { label: 'Lokasi Pintu' },
    // { label: 'Pintu Keluar' },
    { label: 'Durasi Parkir' },
    // { label: 'Tarif' },
    { label: 'Status Member' },
    { label: 'Asal Perusahaan' },
  ],
  rows: [
    {
      no: '1',
      noTiket: 'TK-101',
      tanggalMasuk: '2025-05-09 08:00',
      tanggalKeluar: '2025-05-09 10:00',
      nopol: 'B 1234 XYZ',
      jenisKendaraan: 'Mobil',
      pintuMasuk: 'Gate A',
      pintuKeluar: 'Gate B',
      durasiParkir: '2 jam',
      tarif: 'Rp 10.000',
      statusMember: 'Bukan Member',
      asalPerusahaan: '-',
    },
    {
      no: '2',
      noTiket: 'TK-102',
      tanggalMasuk: '2025-05-09 09:00',
      tanggalKeluar: '2025-05-09 12:00',
      nopol: 'D 1111 JKL',
      jenisKendaraan: 'Mobil',
      pintuMasuk: 'Gate C',
      pintuKeluar: 'Gate D',
      durasiParkir: '3 jam',
      tarif: 'Gratis',
      statusMember: 'Member',
      asalPerusahaan: 'PT Maju Jaya',
    },
    {
      no: '3',
      noTiket: 'TK-103',
      tanggalMasuk: '2025-05-09 10:30',
      tanggalKeluar: '2025-05-09 12:45',
      nopol: 'F 2222 GH',
      jenisKendaraan: 'Motor',
      pintuMasuk: 'Gate A',
      pintuKeluar: 'Gate B',
      durasiParkir: '2 jam 15 menit',
      tarif: 'Rp 5.000',
      statusMember: 'Member',
      asalPerusahaan: 'CV Sukses Abadi',
    },
    {
      no: '4',
      noTiket: 'TK-104',
      tanggalMasuk: '2025-05-09 11:15',
      tanggalKeluar: '2025-05-09 13:30',
      nopol: 'H 3333 IJ',
      jenisKendaraan: 'Mobil',
      pintuMasuk: 'Gate D',
      pintuKeluar: 'Gate A',
      durasiParkir: '2 jam 15 menit',
      tarif: 'Rp 12.000',
      statusMember: 'Bukan Member',
      asalPerusahaan: '-',
    },
    {
      no: '5',
      noTiket: 'TK-105',
      tanggalMasuk: '2025-05-09 14:00',
      tanggalKeluar: '2025-05-09 17:00',
      nopol: 'A 4444 KL',
      jenisKendaraan: 'Mobil',
      pintuMasuk: 'Gate B',
      pintuKeluar: 'Gate C',
      durasiParkir: '3 jam',
      tarif: 'Gratis',
      statusMember: 'Member',
      asalPerusahaan: 'PT Sentosa Raya',
    },
  ],
};
