'use client';

export const tableDataKendaraanOut = {
  columns: [
    { label: 'No.' },
    { label: 'No. Tiket' },
    { label: 'Is Member?' },
    { label: 'Is Manual?' },
    { label: 'Tgl Masuk' },
    { label: 'Tgl Keluar' },
    { label: 'Pintu Masuk' },
    { label: 'Pintu Keluar' },
    { label: 'Nopol' },
    { label: 'Kendaraan' },
    { label: 'Interval' },
    {label: 'Jenis Perhitungan Pembayaran'},
    { label: 'Tarif' },
    { label: 'Denda' },
    // { label: 'Status' },
    // { label: 'Tipe' },
    { label: 'Pembayaran' },
    { label: 'Produk Member' },
    { label: 'No. Kartu Member' },
    { label: 'Petugas' },
    // { label: 'Shift' },
  ],
  rows: [
    {
      no: '1',
      noTiket: 'TK-101',
      isMember: 'Tidak',
      isManual: 'Tidak',
      tglMasuk: '2025-05-09 08:00',
      tglKeluar: '2025-05-09 10:00',
      pintuMasuk: 'Gate A',
      pintuKeluar: 'Gate B',
      nopol: 'B 1234 XYZ',
      kendaraan: 'Mobil',
      interval: '2 jam',
      jenisPerhitunganPembayaran:'flat',
      tarif: 'Rp 10.000',
      denda: 'Rp 0',
      status: 'Selesai',
      tipe: 'Reguler',
      pembayaran: 'Tunai',
      prepaidCard: 'Tidak',
      noPrepaidCard: '-',
      petugas: 'Ahmad',
      shift: 'Pagi',
    },
    {
      no: '2',
      noTiket: 'TK-102',
      isMember: 'Ya',
      isManual: 'Tidak',
      tglMasuk: '2025-05-09 09:00',
      tglKeluar: '2025-05-09 12:00',
      pintuMasuk: 'Gate C',
      pintuKeluar: 'Gate D',
      nopol: 'D 1111 JKL',
      kendaraan: 'Mobil',
      interval: '3 jam',
      jenisPerhitunganPembayaran:'regular',
      tarif: 'Gratis',
      denda: 'Rp 0',
      status: 'Selesai',
      tipe: 'VIP',
      pembayaran: 'Gratis',
      prepaidCard: 'Ya',
      noPrepaidCard: 'PC-2025',
      petugas: 'Budi',
      shift: 'Siang',
    },
    // Tambahkan data lainnya sesuai kebutuhan
  ],
};
